metrics:
  Trip_Count:
    display_name: Order Count
    metric_desc: Order Count
    query: count(bike_id)
    domain: sales
  Total_Sales_Amount:
    display_name: Total Sales Amount
    metric_desc: Total Sales Amount
    query: sum(Sales_Amount)
    domain: sales
